version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

# docker-compose.yml
services:
  web:
    environment:
      - RUN_MIGRATIONS=true
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]

services:
  worker:
    command: ["celery", "-A", "app.celery", "worker"]

