services:
  - type: web
    name: kredilakay
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: FLASK_ENV
        value: production

# KREDILAKAY/render.yaml
services:
  - type: web
    name: kredilakay-web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m alembic upgrade head
    startCommand: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --workers 4
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kredilakay-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free
    numInstances: 1

databases:
  - name: kredilakay-db
    databaseName: kredilakay
    user: kredilakay_admin
    plan: free
    region: miami  # Plus proche d'Haïti
    postgresqlVersion: 14
services:
  - type: web
    name: nginx
    dockerfilePath: ./docker/nginx/Dockerfile
    envVars:
      - key: DOMAIN
        value: kredilakay.ht
      - key: CERTBOT_EMAIL
        value: admin@kredilakay.onrender.com
